import React, { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, Building2, Check, CreditCard, GraduationCap, Mail, ShieldCheck, Target, Users, X } from 'lucide-react';
import { readPlatform, activeAt } from '../utils/platformStore';
import { readOrganizations } from '../utils/demoAccess';
import { acceptInvitation, cancelCourseAssignment, cancelInvitation, createOrder, inviteEmployee, saveLearningPolicy, settleOrder, userForAccount } from '../utils/platformService';
import { BASIC_COURSES, courseAccess, organizationAccess, PLANS, SELLABLE_COURSES } from '../utils/platformPolicy';
import { ALL_DIGCOMP_COURSES } from '../data/courseCatalog';
import { JOB_ROLE_BENCHMARKS } from '../utils/competenceEngine';
import { currency } from '../utils/enterpriseEngine';
import { useOperations } from './TrainingOperations';
import { assignCourse } from '../utils/trainingOperations';
import DemoLessonVideo from './DemoLessonVideo';

const courseTitle = id => ALL_DIGCOMP_COURSES[id]?.title || id;
const date = value => new Date(value).toLocaleDateString('vi-VN');
const orderStatus = { PENDING: 'Chờ thanh toán', PAID: 'Đã thanh toán demo', CANCELLED: 'Đã hủy', FAILED: 'Thất bại' };
export function usePlatform() {
  const [state, setState] = useState(readPlatform);
  useEffect(() => { const refresh=()=>setState(readPlatform()); window.addEventListener('digcomp-platform',refresh); window.addEventListener('digcomp-organizations',refresh); window.addEventListener('storage',refresh); return()=>{window.removeEventListener('digcomp-platform',refresh);window.removeEventListener('digcomp-organizations',refresh);window.removeEventListener('storage',refresh);}; }, []);
  return state;
}
function Notice({ notice }) { return notice ? <div className={notice.error?'pf-alert':'pf-success'} role={notice.error?'alert':'status'}>{notice.text}</div> : null; }
export function CheckoutModal({ user, order, onClose, onSettled }) {
  const [notice,setNotice]=useState(null);
  const [done,setDone]=useState(null);
  function settle(outcome) { try { const result=settleOrder(user.accountId,order.id,outcome);setDone(result.status);onSettled?.(result); } catch(err){setNotice({text:err.message,error:true});} }
  return <div className="modal-overlay"><section className="pf-checkout" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><button className="pf-close" onClick={onClose} aria-label="Đóng thanh toán"><X size={20}/></button><span className="pf-eyebrow">THANH TOÁN MÔ PHỎNG</span><h2 id="checkout-title">{done ? orderStatus[done] : 'Xác nhận quyền học'}</h2><Notice notice={notice}/><div className="pf-order-summary"><CreditCard size={28}/><strong>{order.kind==='course'?courseTitle(order.courseId):PLANS[order.kind].name}</strong><span>{currency(order.amount)}</span><small>{order.kind==='course'?'Quyền học 365 ngày':'Quyền học 30 ngày từ khi thanh toán thành công'}</small><code>{order.id}</code></div><p>Không thu tiền thật, không cần nhập thẻ ngân hàng. Chỉ đơn thành công mới cấp quyền học.</p>{done ? <><div className={done==='PAID'?'pf-success':'pf-alert'}>{done==='PAID'?'Đã cấp quyền học. Bạn có thể tiếp tục ngay.':'Chưa cấp quyền học. Bạn có thể tạo đơn mới để thử lại.'}</div><button className="pf-primary" onClick={onClose}>Đóng & tiếp tục</button></> : <div className="pf-form"><button className="pf-primary" onClick={()=>settle('PAID')}>Mô phỏng thanh toán thành công</button><div className="pf-actions"><button className="pf-secondary" onClick={()=>settle('FAILED')}>Thử thanh toán thất bại</button><button className="pf-link" onClick={()=>settle('CANCELLED')}>Hủy đơn</button></div></div>}</section></div>;
}

export function CoursePreview({ user, course, onBack, onShop, onPurchased }) {
  const [order,setOrder]=useState(null);const [notice,setNotice]=useState(null);
  function buy(kind) {try{setOrder(createOrder(user.accountId,kind,course.id));}catch(err){setNotice({text:err.message,error:true});}}
  return <section className="pf-workspace"><button className="pf-link" onClick={onBack}>← Về lộ trình</button><div className="pf-section-head"><div><span className="pf-eyebrow">BÀI HỌC THỬ · {course.id}</span><h1>{course.title}</h1><p>Xem bài đầu tiên trước khi mở toàn bộ khóa học.</p></div><span className="pf-tag">{courseAccess(user,course.id).label}</span></div><DemoLessonVideo key={course.modules[0].id} module={course.modules[0]}/><article className="pf-card"><h2>{course.modules[0].title}</h2><p>{course.modules[0].theory?.[0]}</p><Notice notice={notice}/><div className="pf-actions">{SELLABLE_COURSES.includes(course.id) && <button className="pf-primary" onClick={()=>buy('course')}>Mua khóa · {currency(course.id.endsWith('-I')?390000:790000)}</button>}<button className="pf-secondary" onClick={onShop}>Xem gói học cá nhân</button></div><p className="pf-muted">Bài học thử không ghi nhận hoàn thành hay cấp xác nhận. Khóa chờ thẩm định chưa mở bán.</p></article>{order && <CheckoutModal user={user} order={order} onClose={()=>{setOrder(null);if(courseAccess(user,course.id).allowed)onPurchased();}}/>}</section>;
}

export function DeploymentWorkspace({ user, onManage }) {
  const state=usePlatform();const organization=readOrganizations().find(item=>item.id===user.organizationId);const operations=useOperations(user.organizationId);
  const policy=organizationAccess(organization);
  const [limit,setLimit]=useState(policy.courseLimit);
  const [allowed,setAllowed]=useState(policy.allowedCourseIds);
  const [invite,setInvite]=useState({name:'',email:'',roleId:organization.roles[0]?.id,courseIds:[]});
  const [grant,setGrant]=useState({employeeId:'',courseId:'A1-F',dueDate:''});
  useEffect(() => { if (!policy.allowedCourseIds.includes(grant.courseId)) setGrant(previous => ({...previous, courseId: policy.allowedCourseIds[0] || ''})); }, [policy.allowedCourseIds.join(','), grant.courseId]);
  const [notice,setNotice]=useState(null);const [order,setOrder]=useState(null);
  const invitations=state.invitations.filter(item=>item.organizationId===organization.id);
  const members=state.memberships.filter(item=>item.organizationId===organization.id && item.status==='ACTIVE');
  const pending=invitations.filter(item=>item.status==='PENDING' && activeAt(item.expiresAt));
  const permitted=policy.plan==='team'?SELLABLE_COURSES:BASIC_COURSES;
  function act(fn,text){try{const result=fn();setNotice({text});return result;}catch(err){setNotice({text:err.message,error:true});return null;}}
  const toggle=(list,id)=>list.includes(id)?list.filter(x=>x!==id):[...list,id];
  return <div className="pf-workspace"><div className="pf-section-head"><div><span className="pf-eyebrow">TRIỂN KHAI DOANH NGHIỆP</span><h1>{organization.name}</h1><p>Cấu hình quyền học trước, mời đúng người, theo dõi đúng khóa.</p></div><button className="pf-secondary" onClick={onManage}>Quản trị đào tạo <ArrowRight size={16}/></button></div><Notice notice={notice}/><div className="pf-onboarding"><span className="complete"><Check size={16}/> Email đã xác thực</span><span className={policy.configured?'complete':''}>02 · Cấu hình khóa</span><span className={members.length?'complete':''}>03 · Nhân viên xác nhận</span><span>04 · Học & thẩm định</span></div>
    <div className="pf-stats"><article><Building2/><span>Gói hiện tại</span><strong>{policy.plan==='team'?'Growth':'Dùng thử 14 ngày'}</strong><small>{policy.active?`Đến ${date(policy.expiresAt)}`:'Đã hết hạn'}</small></article><article><Users/><span>Chỗ đang dùng / giữ</span><strong>{members.length + pending.length}/{policy.seats}</strong><small>{members.length} đã tham gia · {pending.length} chờ</small></article><article><BookOpen/><span>Giới hạn mỗi người</span><strong>{policy.courseLimit} khóa</strong><small>{policy.allowedCourseIds.length} khóa trong danh mục</small></article></div>
    <div className="pf-deployment-grid"><form className="pf-card pf-form" onSubmit={e=>{e.preventDefault();act(()=>saveLearningPolicy(user.accountId,organization.id,Number(limit),allowed),'Đã lưu cấu hình. Có thể mời nhân viên và chọn khóa cụ thể.');}}><span className="pf-eyebrow">BƯỚC 01</span><h2>Cấu hình chương trình</h2><label>Tối đa khóa mỗi nhân viên<input required type="number" min="1" max={policy.maxCourseLimit} value={limit} onChange={e=>setLimit(e.target.value)}/></label><fieldset className="pf-course-checks"><legend>Danh mục được doanh nghiệp tài trợ</legend>{permitted.map(id=><label className="pf-checkbox" key={id}><input type="checkbox" checked={allowed.includes(id)} onChange={()=>setAllowed(toggle(allowed,id))}/><span>{id} · {courseTitle(id)}</span></label>)}</fieldset><button className="pf-primary" type="submit">Lưu cấu hình đào tạo</button><button className="pf-link" type="button" onClick={()=>{const result=act(()=>createOrder(user.accountId,'team',undefined,organization.id),'Đã tạo đơn nâng gói.');if(result)setOrder(result);}}>{policy.plan==='team'?'Gia hạn Growth':'Nâng lên Growth'} · {currency(PLANS.team.price)}/30 ngày</button><small>Growth: 20 nhân viên · tối đa 10 khóa/người. Nâng gói không tự thay đổi danh mục đã chọn.</small></form>
    <form className="pf-card pf-form" onSubmit={e=>{e.preventDefault();const result=act(()=>inviteEmployee(user.accountId,organization.id,invite),'Lời mời đã vào hộp thư demo. Nhân viên đăng ký/đăng nhập đúng email để nhận.');if(result)setInvite({...invite,name:'',email:'',courseIds:[]});}}><span className="pf-eyebrow">BƯỚC 02</span><h2>Mời nhân viên bằng email</h2><label>Họ tên nhân viên<input required value={invite.name} onChange={e=>setInvite({...invite,name:e.target.value})}/></label><label>Email nhân viên<input required type="email" placeholder="nhanvien@gmail.com hoặc email công ty" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></label><label>Vị trí trong doanh nghiệp<select value={invite.roleId} onChange={e=>setInvite({...invite,roleId:e.target.value})}>{organization.roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><fieldset className="pf-course-checks"><legend>Khóa giao khi xác nhận · {invite.courseIds.length}/{policy.courseLimit}</legend>{policy.allowedCourseIds.map(id=><label className="pf-checkbox" key={id}><input type="checkbox" checked={invite.courseIds.includes(id)} onChange={()=>setInvite({...invite,courseIds:toggle(invite.courseIds,id)})}/>{id} · {courseTitle(id)}</label>)}</fieldset><button className="pf-primary" disabled={!policy.configured||!policy.active}>Tạo lời mời demo <Mail size={16}/></button><small>Lời mời giữ một chỗ trong 7 ngày. Chỉ tạo hồ sơ nhân viên và giao khóa khi người nhận đồng ý.</small></form></div>
    <section className="pf-card"><h2>Lời mời & thành viên</h2>{!invitations.length && <p>Chưa có lời mời. Hãy hoàn tất hai bước trên.</p>}{invitations.map(item=><div className="pf-list-row" key={item.id}><div><strong>{item.name} · {item.email}</strong><small>{organization.roles.find(role=>role.id===item.roleId)?.name} · {item.courseIds.length} khóa · đến {date(item.expiresAt)}</small></div><span className="pf-tag">{item.status==='ACCEPTED'?'Đã tham gia':item.status==='CANCELLED'?'Đã thu hồi':activeAt(item.expiresAt)?'Chờ xác nhận':'Hết hạn'}</span>{item.status==='PENDING' && <button className="pf-link" onClick={()=>act(()=>cancelInvitation(user.accountId,item.id),'Đã thu hồi lời mời.')}>Thu hồi lời mời</button>}</div>)}</section>
    <section className="pf-card"><div className="pf-section-head"><div><span className="pf-eyebrow">SAU KHI NHÂN VIÊN THAM GIA</span><h2>Phân bổ khóa & tiến độ</h2></div><button className="pf-link" onClick={onManage}>Khung năng lực, bài thực hành và báo cáo <ArrowRight size={15}/></button></div>{members.length ? <><form className="pf-grant-form pf-form" onSubmit={e=>{e.preventDefault();act(()=>assignCourse(organization,grant.employeeId,grant.courseId,grant.dueDate,`admin-${organization.id}`),'Đã giao thêm khóa cho nhân viên.');}}><label>Nhân viên đã xác nhận<select required value={grant.employeeId} onChange={e=>setGrant({...grant,employeeId:e.target.value})}><option value="">Chọn nhân viên</option>{members.map(item=><option key={item.id} value={item.employeeId}>{organization.employees.find(person=>person.id===item.employeeId)?.name}</option>)}</select></label><label>Khóa bổ sung<select value={grant.courseId} onChange={e=>setGrant({...grant,courseId:e.target.value})}>{policy.allowedCourseIds.map(id=><option key={id} value={id}>{id} · {courseTitle(id)}</option>)}</select></label><label>Hạn học<input required type="date" value={grant.dueDate} onChange={e=>setGrant({...grant,dueDate:e.target.value})}/></label><button className="pf-primary">Giao thêm khóa</button></form>{operations.assignments.filter(item=>item.status!=='CANCELLED').map(item=><div className="pf-list-row" key={item.id}><div><strong>{courseTitle(item.courseId)}</strong><small>{organization.employees.find(person=>person.id===item.employeeId)?.name} · hạn {date(item.dueDate)}</small></div><span className="pf-tag">{operations.enrollments.find(enrollment=>enrollment.assignmentId===item.id)?.progress || 0}%</span><button className="pf-link" onClick={()=>act(()=>cancelCourseAssignment(user.accountId,organization.id,item.id),'Đã thu hồi phân bổ; lịch sử học được giữ lại.')}>Thu hồi khóa</button></div>)}</> : <p>Nhân viên xuất hiện tại đây sau khi xác nhận lời mời.</p>}</section>
    <details className="pf-card"><summary>Đơn hàng doanh nghiệp & lịch sử triển khai</summary>{state.orders.filter(item=>item.organizationId===organization.id).map(item=><div className="pf-list-row" key={item.id}><span>{PLANS[item.kind]?.name} · {currency(item.amount)}</span><span>{orderStatus[item.status]}</span>{item.status==='PENDING' && <button className="pf-link" onClick={()=>setOrder(item)}>Tiếp tục thanh toán</button>}</div>)}{state.audit.filter(item=>item.actorId===user.accountId).slice(0,8).map(item=><p key={item.id}>{date(item.createdAt)} · {item.action} · {item.detail}</p>)}</details>
    {order && <CheckoutModal user={user} order={order} onClose={()=>setOrder(null)}/>}</div>;
}

export function AccountWorkspace({ user, onSwitch }) {
  const state=usePlatform();const [notice,setNotice]=useState(null);const [order,setOrder]=useState(null);
  const invites=state.invitations.filter(item=>item.email===user.email);
  const memberships=state.memberships.filter(item=>item.accountId===user.accountId && item.status==='ACTIVE');
  const organizations=readOrganizations();
  const owned=organizations.filter(item=>item.ownerAccountId===user.accountId);
  return <div className="pf-workspace"><div className="pf-section-head"><div><span className="pf-eyebrow">{user.role==='enterprise_admin'?'TÀI KHOẢN QUẢN TRỊ':'TÀI KHOẢN & LỜI MỜI'}</span><h1>{user.name}</h1><p><ShieldCheck size={15}/> {user.email} · Email đã xác thực</p></div></div><Notice notice={notice}/><section className="pf-card"><h2>Không gian của bạn</h2><div className="pf-actions"><button className="pf-secondary" onClick={()=>onSwitch(userForAccount(user.accountId,'personal'))}><GraduationCap size={17}/> Cá nhân & mục tiêu nghề nghiệp</button>{owned.map(org=><button className="pf-secondary" key={org.id} onClick={()=>onSwitch(userForAccount(user.accountId,org.id))}><Building2 size={17}/> Quản trị {org.name}</button>)}{memberships.map(item=><button className="pf-secondary" key={item.id} onClick={()=>onSwitch(userForAccount(user.accountId,item.organizationId))}><Users size={17}/> Nhân viên · {organizations.find(org=>org.id===item.organizationId)?.name}</button>)}</div><p className="pf-muted">Quyền mua cá nhân đi theo tài khoản. Kết quả học và mục tiêu được lưu riêng theo không gian; doanh nghiệp theo dõi hoạt động trong không gian của họ.</p></section>
    {user.role!=='enterprise_admin' && <><section className="pf-card"><h2>Lời mời doanh nghiệp</h2>{!invites.length && <p>Chưa có lời mời. Doanh nghiệp cần mời đúng email <strong>{user.email}</strong>.</p>}{invites.map(item=><article className="pf-invitation" key={item.id}><div><span className="pf-tag">{item.status==='ACCEPTED'?'Đã tham gia':item.status==='CANCELLED'?'Đã thu hồi':activeAt(item.expiresAt)?'Chờ bạn xác nhận':'Đã hết hạn'}</span><h3>{organizations.find(org=>org.id===item.organizationId)?.name}</h3><p>Vị trí: {organizations.find(org=>org.id===item.organizationId)?.roles.find(role=>role.id===item.roleId)?.name}</p><p>{item.courseIds.map(courseTitle).join(' · ')}</p><small>Hết hạn {date(item.expiresAt)}. Khi tham gia, quản trị viên xem được tiến độ học và bài thực hành trong doanh nghiệp.</small></div>{item.status==='PENDING' && activeAt(item.expiresAt) && <button className="pf-primary" onClick={()=>{try{const next=acceptInvitation(user.accountId,item.id);onSwitch(next);}catch(err){setNotice({error:true,text:err.message});}}}>Đồng ý & vào doanh nghiệp <ArrowRight size={16}/></button>}</article>)}</section>
    <section className="pf-card"><h2>Quyền học cá nhân</h2>{!state.entitlements.some(item=>item.accountId===user.accountId) && <p>Bạn đang có 5 khóa cơ bản miễn phí. Mở “Khám phá & gói học” để học nâng cao.</p>}{state.entitlements.filter(item=>item.accountId===user.accountId).map(item=><div className="pf-list-row" key={item.id}><strong>{item.kind==='personal'?PLANS.personal.name:courseTitle(item.courseIds[0])}</strong><span>{activeAt(item.expiresAt)?'Còn hiệu lực':'Đã hết hạn'} · {date(item.expiresAt)}</span></div>)}</section>
    <section className="pf-card"><h2>Đơn mua cá nhân</h2>{state.orders.filter(item=>item.accountId===user.accountId && item.kind!=='team').map(item=><div className="pf-list-row" key={item.id}><div><strong>{item.kind==='course'?courseTitle(item.courseId):PLANS.personal.name}</strong><small>{date(item.createdAt)} · {currency(item.amount)}</small></div><span className="pf-tag">{orderStatus[item.status]}</span>{item.status==='PENDING' && <button className="pf-link" onClick={()=>setOrder(item)}>Tiếp tục thanh toán</button>}</div>)}</section></>}{order && <CheckoutModal user={user} order={order} onClose={()=>setOrder(null)}/>}</div>;
}

export function LearningMarketplace({ user, selectedRole, onSelectRole, onLearning, onOpenCourse }) {
  const platform = usePlatform();
  const [roleId,setRoleId]=useState(selectedRole?.roleId || JOB_ROLE_BENCHMARKS[0].roleId);
  const [company,setCompany]=useState('');const [positionId,setPositionId]=useState('');const [level,setLevel]=useState('all');
  const [order,setOrder]=useState(null);const [notice,setNotice]=useState(null);
  const organizations=readOrganizations().filter(item=>!item.ownerAccountId);
  const targetCompany=organizations.find(item=>item.id===company);
  const position=targetCompany?.roles.find(item=>item.id===positionId);
  const role=JOB_ROLE_BENCHMARKS.find(item=>item.roleId===(position?.benchmark || roleId)) || JOB_ROLE_BENCHMARKS[0];
  const hasPersonalPlan = platform.entitlements.some(item => item.accountId === user.accountId && item.kind === 'personal' && activeAt(item.expiresAt));
  const courses=Object.values(ALL_DIGCOMP_COURSES).filter(item=>level==='all'||item.id.endsWith(`-${level}`)).sort((a,b)=>a.areaId.localeCompare(b.areaId)||['F','I','A'].indexOf(a.id.slice(-1))-['F','I','A'].indexOf(b.id.slice(-1)));
  function startGoal() {
    const next=position ? {...role,roleTitle:`${position.name} · ${targetCompany.name}`,goalKey:`${targetCompany.id}:${position.id}`,competencies:role.competencies.map((item,i)=>({...item,reqLevelNumber:position.requirements[i].level,reqLevelLabel:`Mức ${position.requirements[i].level}/6 theo vị trí`,isCore:position.requirements[i].mandatory}))} : {...role,goalKey:role.roleId};
    onSelectRole(next);onLearning();
  }
  return <div className="pf-workspace"><div className="pf-section-head"><div><span className="pf-eyebrow">HỌC CHO BƯỚC TIẾN TIẾP THEO</span><h1>{user.role==='employee'?'Mở rộng ngoài kế hoạch doanh nghiệp':'Bạn muốn tiến đến vị trí nào?'}</h1><p>Khám phá lộ trình theo mục tiêu, học cơ bản miễn phí và mở thêm kỹ năng chuyên sâu.</p></div></div><Notice notice={notice}/><section className="pf-card"><h2>Cách mua khóa học trong bản mẫu</h2><ol><li>Chọn khóa cơ bản để học miễn phí, hoặc mở khóa chuyên sâu để xem bài học thử.</li><li>Mua riêng một khóa, hoặc chọn gói cá nhân 30 ngày để mở các khóa đang sẵn sàng.</li><li>Trong cửa sổ thanh toán mô phỏng, chọn thành công để được cấp quyền học. Đơn thất bại hoặc bị hủy không cấp quyền.</li></ol><p className="pf-muted">Giá và thanh toán chỉ để xem luồng giao diện. Không thu tiền thật.</p></section>{user.role!=='employee' && <section className="pf-card pf-goal"><Target size={32}/><div><h2>Thiết lập mục tiêu nghề nghiệp</h2><div className="pf-form pf-form-two"><label>Vị trí mục tiêu<select value={roleId} onChange={e=>{setRoleId(e.target.value);setCompany('');setPositionId('');}}>{JOB_ROLE_BENCHMARKS.map(item=><option key={item.roleId} value={item.roleId}>{item.roleTitle}</option>)}</select></label><label>Tham khảo doanh nghiệp mẫu<select value={company} onChange={e=>{setCompany(e.target.value);setPositionId(organizations.find(item=>item.id===e.target.value)?.roles[0]?.id||'');}}><option value="">Khung nghề nghiệp chung</option>{organizations.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{targetCompany && <label>Vị trí tại doanh nghiệp<select value={positionId} onChange={e=>setPositionId(e.target.value)}>{targetCompany.roles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}</div><div className="pf-actions"><button className="pf-primary" onClick={startGoal}>Lập lộ trình cho mục tiêu này <ArrowRight size={15}/></button><small>Mục tiêu đào tạo, không phải tin tuyển dụng hay cam kết được tuyển.</small></div></div></section>}
    {user.role==='employee' && <div className="pf-success">Khóa doanh nghiệp giao được tài trợ theo gói của doanh nghiệp. Mua thêm là lựa chọn cá nhân, tính vào đơn riêng của bạn.</div>}
    <div className="pf-section-head"><h2>Thư viện khóa học</h2><div className="pf-role-tabs">{[['all','Tất cả'],['F','Cơ bản'],['I','Trung cấp'],['A','Nâng cao']].map(([id,label])=><button key={id} className={level===id?'active':''} onClick={()=>setLevel(id)}>{label}</button>)}</div></div><div className="pf-course-grid">{courses.map(course=>{const access=courseAccess(user,course.id);const req=role.competencies.find(item=>item.id===course.areaId);return <article className="pf-course-card" key={course.id}><div className={`pf-course-art area-${course.id[1]}`}><BookOpen size={30}/><span>{course.id} · {course.id.endsWith('-F')?'Cơ bản':course.id.endsWith('-I')?'Trung cấp':'Nâng cao'}</span></div><div><span className="pf-tag">{access.label}</span><h3>{course.title}</h3><p>{course.modules.length} bài · {course.duration}</p><small>{req?.isCore?'Năng lực trọng tâm':'Năng lực hỗ trợ'} · {role.roleTitle}</small><button className="pf-link" onClick={()=>onOpenCourse(course)}>{access.allowed?'Vào học':'Xem bài học thử'} <ArrowRight size={15}/></button></div></article>;})}</div>
    <section className="pf-upgrade"><div><span className="pf-eyebrow">ĐẦU TƯ CHO MỤC TIÊU CỦA BẠN</span><h2>{PLANS.personal.name}</h2><p>{PLANS.personal.description}</p><small>Áp dụng cho {SELLABLE_COURSES.length} khóa sẵn sàng; các khóa chờ thẩm định vẫn có bài học thử.</small></div><div><strong>{currency(PLANS.personal.price)}<small> / 30 ngày</small></strong><button className="pf-primary" onClick={()=>{try{setOrder(createOrder(user.accountId,'personal'));}catch(err){setNotice({error:true,text:err.message});}}} disabled={hasPersonalPlan}>{hasPersonalPlan ? 'Gói đang có hiệu lực' : 'Chọn gói cá nhân'} <ArrowRight size={15}/></button></div></section>{order && <CheckoutModal user={user} order={order} onClose={()=>setOrder(null)}/>}</div>;
}
