import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { enterpriseTrialService as service, type TrialAnswerDto, type TrialContextDto, type TrialPathItemDto } from '@/services/enterprise-trial.service';
import { useCurrentUser } from '@/hooks/use-current-user';
import { trialQueryKey, useTrialMutation, useTrialQuery } from './trial-queries';
import { data, ErrorText, Panel, StateBadge, inputClass, buttonClass } from './trial-ui';
import { TrialResultDetails } from './TrialResultDetails';

function LearningItem({ item, writable }: { item: TrialPathItemDto; writable: boolean }) {
  const [percent, setPercent] = useState(item.progressPercent); const start = useTrialMutation(() => service.startPathItem(item.id)); const progress = useTrialMutation(() => service.progressPathItem(item.id, percent));
  const content = useMutation({ mutationFn: () => data(service.pathContent(item.id)) });
  return <article className="space-y-3 rounded-xl border border-ent-line p-4"><h3 className="font-medium">{item.title}</h3><StateBadge state={item.status} /><p className="text-sm">{item.version} · {item.progressPercent}%</p><p className="text-sm">Vì sao được gợi ý: {item.reasons.join(' · ')}</p>{item.prerequisites.length > 0 && <p className="text-sm">Tiên quyết: {item.prerequisites.join(' · ')}{!item.allowedToStart && ' · Chưa thể bắt đầu'}</p>}<ErrorText error={start.error || progress.error || content.error} />
    <div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={!writable || !item.allowedToStart || item.status !== 'not_started' || start.isPending} onClick={() => start.mutate(undefined)}>Bắt đầu {item.title}</button><button className={buttonClass} disabled={!item.allowedToStart || item.status === 'not_started' || content.isPending} onClick={() => content.mutate()}>Đọc {item.title}</button></div>
    {content.data && <section aria-label={`Nội dung ${item.title}`} className="whitespace-pre-wrap break-words rounded-lg bg-ent-raised p-4"><h4 className="font-medium">{content.data.title} · {content.data.version}</h4><p className="mt-2 text-sm">{content.data.body}</p></section>}
    {item.status !== 'not_started' && <div className="flex flex-wrap items-end gap-3"><label className="grid gap-2 text-sm">Tiến độ {item.title}<input type="number" min={item.progressPercent} max={100} step={1} className={inputClass} value={percent} disabled={!writable} onChange={e => setPercent(Number(e.target.value))} /></label><button className={buttonClass} disabled={!writable || progress.isPending || !Number.isInteger(percent) || percent < item.progressPercent || percent > 100} onClick={() => progress.mutate(undefined)}>Lưu tiến độ {item.title}</button></div>}
  </article>;
}

export function EmployeeTrialPanel({ context, writable }: { context: TrialContextDto; writable: boolean }) {
  const diagnostic = useTrialQuery('diagnostic', service.diagnostic); const result = useTrialQuery('result', service.result); const path = useTrialQuery('path', service.path); const cache = useQueryClient(); const user = useCurrentUser(state => state.user);
  const [questionIndex, setQuestionIndex] = useState(0); const start = useTrialMutation(() => service.startDiagnostic()); const submit = useTrialMutation((id: string) => service.submitDiagnostic(id));
  const save = useMutation({ mutationFn: (answers: TrialAnswerDto[]) => { const attempt = diagnostic.data!; return data(service.saveAnswers(attempt.attemptId, attempt.revision, answers)); }, onSuccess: attempt => cache.setQueryData(trialQueryKey(user, 'diagnostic'), attempt) });
  const attempt = diagnostic.data; const question = attempt?.questions[Math.min(questionIndex, attempt.questions.length - 1)];
  const writeDiagnostic = writable && context.allowedActions.includes('diagnostic'); const writeLearning = writable && context.allowedActions.includes('learning');
  const errors = diagnostic.error || result.error || path.error || start.error || save.error || submit.error;
  return <div className="space-y-6"><ErrorText error={errors} />
    <Panel title="Đánh giá đầu vào">{diagnostic.isPending ? <p role="status">Đang tải bài đánh giá…</p> : !attempt ? <div className="space-y-3"><p>Chưa đánh giá. Vị trí: {context.selectedPosition?.name ?? 'Chưa chọn'} · Chuẩn: {context.selectedPosition?.requirementVersion ?? 'Chưa có'}</p><p className="text-sm">Tối đa {context.limits.maxDiagnosticAttempts} lượt. Câu trả lời được lưu từng bước; nộp bài để nhận kết quả theo yêu cầu vị trí.</p><button className={buttonClass} disabled={!writeDiagnostic || !context.selectedPosition || start.isPending || diagnostic.isError} onClick={() => start.mutate(undefined)}>Bắt đầu đánh giá</button></div> : <div className="space-y-4"><p className="text-sm">{attempt.positionName} · {attempt.requirementVersion} · {attempt.assessmentVersion} · {attempt.rubricVersion}</p><StateBadge state={attempt.status} />
      {attempt.status === 'in_progress' && <><p role="status" className="text-sm">{save.isPending ? 'Đang lưu…' : save.isError ? 'Chưa lưu thay đổi. Thử lại hoặc tải bài từ máy chủ.' : save.isSuccess ? 'Đã lưu' : 'Tiếp tục từ câu đã lưu'} · {attempt.savedAnswers.length}/{attempt.questions.length} câu đã trả lời</p><progress className="w-full" value={attempt.savedAnswers.length} max={Math.max(1, attempt.questions.length)} aria-label="Tiến độ trả lời" />
        {question && <fieldset className="space-y-3" disabled={!writeDiagnostic || save.isPending || submit.isPending || diagnostic.isFetching}><legend className="mb-3 font-medium">Câu {questionIndex + 1}: {question.text}</legend>{question.options.map(option => <label key={option.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-ent-line p-3 text-sm"><input type="radio" name={question.id} checked={attempt.savedAnswers.some(answer => answer.questionId === question.id && answer.optionId === option.id)} onChange={() => save.mutate([...attempt.savedAnswers.filter(answer => answer.questionId !== question.id), { questionId: question.id, optionId: option.id }])} />{option.text}</label>)}</fieldset>}
        <div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={questionIndex === 0} onClick={() => setQuestionIndex(index => index - 1)}>Câu trước</button><button className={buttonClass} disabled={questionIndex >= attempt.questions.length - 1} onClick={() => setQuestionIndex(index => index + 1)}>Câu tiếp</button><button className={buttonClass} onClick={() => { save.reset(); void diagnostic.refetch(); }}>Tải bài đã lưu</button></div>
        <details className="rounded-xl border border-ent-line p-3" open><summary>Xác nhận nộp bài</summary><p className="my-3 text-sm">Còn {attempt.questions.length - attempt.savedAnswers.length} câu chưa trả lời. Máy chủ chấm theo rubric; phần chưa đo đủ có thể là Chưa đủ dữ liệu. Sau nộp không sửa câu trả lời.</p><button className={buttonClass} disabled={!writeDiagnostic || save.isPending || save.isError || submit.isPending || diagnostic.isFetching} onClick={() => submit.mutate(attempt.attemptId)}>Nộp bài đánh giá</button></details></>}
    </div>}</Panel>
    <Panel title="Kết quả so với vị trí của bạn">{result.data ? <TrialResultDetails result={result.data} /> : <p className="text-sm">Chưa có kết quả đã nộp; chưa đánh giá không phải điểm 0.</p>}</Panel>
    <Panel title="Lộ trình của tôi">{path.data ? <div className="space-y-4"><StateBadge state={path.data.state} />{path.data.missingContentReasons.map(reason => <p key={reason} className="text-sm">{reason}</p>)}{path.data.items.map(item => <LearningItem key={`${item.id}-${item.progressPercent}`} item={item} writable={writeLearning} />)}{path.data.items.length === 0 && <p>Không có mục học trong phạm vi kết quả này. Xem lý do phía trên.</p>}</div> : <p className="text-sm">Lộ trình xuất hiện sau khi nộp đánh giá; quản lý không cần giao khóa.</p>}</Panel>
  </div>;
}
