import { useState } from 'react';
import { Link } from 'react-router-dom';
import { enterpriseTrialService as service, type TrialContextDto } from '@/services/enterprise-trial.service';
import { DataTable } from '@/components/shared/DataTable';
import { WizardShell } from '@/components/shared/WizardShell';
import { useTrialMutation, useTrialQuery } from './trial-queries';
import { ErrorText, Panel, StateBadge, buttonClass, inputClass, safeDevelopmentPath } from './trial-ui';

export function OwnerTrialPanel({ context, writable }: { context: TrialContextDto; writable: boolean }) {
  const catalog = useTrialQuery('catalog', service.catalog); const invitations = useTrialQuery('invitations', service.invitations);
  const [department, setDepartment] = useState('Nhóm thử'); const [form, setForm] = useState({ name: '', email: '', role: 'Employee' as 'Employee' | 'Manager' });
  const [developmentLink, setDevelopmentLink] = useState<string | null>(null);
  const position = useTrialMutation((key: string) => service.selectPosition(key, department)); const invite = useTrialMutation(() => service.invite(form.name, form.email, form.role)); const resend = useTrialMutation((id: string) => service.resendInvitation(id));
  const canInvite = writable && context.allowedActions.includes('invite') && !!context.selectedPosition && context.usage.accounts + context.usage.pendingInvitations < context.limits.maxAccounts;
  const steps = [{ id: 'position', label: 'Chọn vị trí' }, { id: 'invite', label: 'Mời người tham gia' }];
  return <div className="space-y-6"><ErrorText error={catalog.error || invitations.error || position.error || invite.error || resend.error} />
    <WizardShell title={context.selectedPosition ? 'Mời vào đúng vị trí đã chọn' : 'Chọn một vị trí đủ điều kiện'} description="Chuẩn vị trí được chốt; không tự đổi tiêu chuẩn theo tên nhập." steps={steps} current={context.selectedPosition ? 1 : 0} completed={new Set(context.checklist.filter(item => item.complete).map(item => item.key))}>
      {!context.selectedPosition ? <div className="space-y-4"><label className="grid gap-2 text-sm">Tên bộ phận<input className={inputClass} value={department} onChange={e => setDepartment(e.target.value)} required maxLength={200} /></label>{catalog.data?.map(item => <article key={item.catalogKey} className="space-y-2 rounded-xl border border-ent-line p-4"><h3 className="font-semibold">{item.name}</h3><p className="text-sm">{item.requirementVersion} · {item.assessmentVersion} · {item.rubricVersion}</p>{item.requirements.map(requirement => <p key={requirement.competencyId} className="text-sm">{requirement.name}: mức {requirement.requiredLevel}, tối thiểu {requirement.minimumAnswers} câu đo</p>)}{item.missingReasons.length > 0 && <p>{item.missingReasons.join(' · ')}</p>}<button className={buttonClass} disabled={!writable || !context.allowedActions.includes('select_position') || !item.eligible || position.isPending || !department.trim()} onClick={() => position.mutate(item.catalogKey)}>Dùng vị trí {item.name}</button></article>)}{catalog.isPending && <p role="status">Đang tải vị trí…</p>}</div> : <p className="text-sm">Vị trí đã chốt: {context.selectedPosition.name} · {context.selectedPosition.requirementVersion}</p>}
    </WizardShell>
    <Panel title="Mời người tham gia"><p className="text-sm">Ghế: {context.usage.accounts} tài khoản + {context.usage.pendingInvitations} lời mời đang chờ / {context.limits.maxAccounts}. Chủ sở hữu cũng dùng một ghế.</p>{!canInvite && <p className="text-sm">Cần vị trí đã chọn, trial còn ghi được và ghế còn trống.</p>}<form className="grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); if (canInvite && !invite.isPending) invite.mutate(undefined, { onSuccess: value => { setDevelopmentLink(safeDevelopmentPath(value.developmentLink, 'accept')); setForm(previous => ({ ...previous, name: '', email: '' })); } }); }}>
      <label className="grid gap-2 text-sm">Họ tên người tham gia<input className={inputClass} required maxLength={200} value={form.name} onChange={e => setForm(previous => ({ ...previous, name: e.target.value }))} disabled={!canInvite} /></label>
      <label className="grid gap-2 text-sm">Email người tham gia<input className={inputClass} type="email" required value={form.email} onChange={e => setForm(previous => ({ ...previous, email: e.target.value }))} disabled={!canInvite} /></label>
      <label className="grid gap-2 text-sm">Vai trò<select className={inputClass} value={form.role} onChange={e => setForm(previous => ({ ...previous, role: e.target.value as 'Employee' | 'Manager' }))} disabled={!canInvite}><option value="Employee">Nhân viên</option><option value="Manager">Quản lý</option></select></label><button className={buttonClass} disabled={!canInvite || invite.isPending}>Gửi lời mời</button>
    </form>{invite.isSuccess && <p role="status">Đã ghi nhận lời mời. Chờ người tham gia xác nhận.</p>}{developmentLink && <p>Development-only: <Link className="underline" to={developmentLink}>Mở lời mời demo</Link></p>}</Panel>
    <Panel title="Trạng thái lời mời"><DataTable data={invitations.data ?? []} isLoading={invitations.isPending} keyExtractor={row => row.id} emptyTitle="Chưa có lời mời" emptyDescription="Chọn vị trí rồi mời người tham gia." forceScrollX columns={[{ key: 'name', header: 'Người tham gia', cell: row => <div className="max-w-64 break-words">{row.name}<p className="text-xs">{row.email}</p></div> }, { key: 'state', header: 'Trạng thái', cell: row => <><StateBadge state={row.state} /><p className="text-xs">{row.role}</p></> }, { key: 'dates', header: 'Thời hạn', cell: row => <p className="text-xs">Gửi: {new Date(row.sentAt).toLocaleString('vi-VN')}<br />Hạn: {new Date(row.expiresAt).toLocaleString('vi-VN')}</p> }, { key: 'resend', header: 'Thao tác', cell: row => <div className="space-y-2"><button className={buttonClass} disabled={!writable || !row.canResend || resend.isPending} onClick={() => resend.mutate(row.id, { onSuccess: value => setDevelopmentLink(safeDevelopmentPath(value.developmentLink, 'accept')) })}>Gửi lại {row.name}</button>{safeDevelopmentPath(row.developmentLink, 'accept') && <p className="text-xs">Development-only: <Link className="underline" to={safeDevelopmentPath(row.developmentLink, 'accept')!}>Lời mời {row.name}</Link></p>}</div> }]} /></Panel>
  </div>;
}
