import React, { useState } from 'react';
import { ArrowRight, ArrowLeft, BookOpen, Building2, Check, GraduationCap, Mail, ShieldCheck, Target, Zap } from 'lucide-react';
import LoginPage from './LoginPage';
import FrameworkWorkspace from './FrameworkWorkspace';
import { ALL_DIGCOMP_COURSES } from '../data/courseCatalog';
import { JOB_ROLE_BENCHMARKS } from '../utils/competenceEngine';
import { loginAccount, registerAccount, resendVerification, verifyAccount } from '../utils/platformService';
import { readPlatform, normalizeEmail } from '../utils/platformStore';
import { PLANS } from '../utils/platformPolicy';
import { currency } from '../utils/enterpriseEngine';
import './platform.css';

export function DemoMailbox({ email }) {
  const [open, setOpen] = useState(false);
  const messages = readPlatform().mail.filter(item => item.to === normalizeEmail(email));
  return <section className="pf-mailbox"><button className="pf-link" type="button" onClick={() => setOpen(!open)}><Mail size={16}/> {open ? 'Đóng hộp thư demo' : 'Mở hộp thư demo'}</button>{open && <div><p>Email chỉ được mô phỏng trong trình duyệt này, chưa gửi tới hộp thư thật.</p>{messages.length ? messages.map(mail => <article key={mail.id}><strong>{mail.subject}</strong><small>Đến: {mail.to} · {new Date(mail.createdAt).toLocaleString('vi-VN')}</small>{mail.kind === 'VERIFY' ? <><span>Mã xác thực: <code>{mail.code}</code></span><small>{mail.usedAt ? 'Mã đã dùng / được thay thế' : 'Hiệu lực 15 phút, tối đa 5 lần thử'}</small></> : <p>Đăng ký hoặc đăng nhập bằng đúng email này, mở “Tài khoản & lời mời” để xác nhận tham gia doanh nghiệp.</p>}</article>) : <p>Chưa có thư gửi đến email này.</p>}</div>}</section>;
}

export default function AcquisitionPortal({ onLogin }) {
  const [page, setPage] = useState('landing');
  const [form, setForm] = useState({ type: 'personal', name: '', email: '', password: '', company: '', sector: '', size: 20, targetRole: 'marketing_specialist', consent: false });
  const [code, setCode] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [role, setRole] = useState(JOB_ROLE_BENCHMARKS[0]);
  function go(next, type) { setPage(next); setError(''); setMessage(''); if (type) setForm(previous => ({ ...previous, type })); window.scrollTo(0, 0); }
  const field = (key, value) => setForm(previous => ({ ...previous, [key]: value }));
  async function submit(event) {
    event.preventDefault(); setError(''); setMessage(''); setBusy(true);
    try {
      if (page === 'register') { await registerAccount(form); setPage('verify'); setMessage('Đã tạo tài khoản chờ xác thực. Mở hộp thư demo để lấy mã.'); }
      else if (page === 'verify') { verifyAccount(form.email, code); setCode(''); setPage('login'); setMessage('Email đã được xác thực. Đăng nhập để bắt đầu.'); }
      else { onLogin(await loginAccount(form.email, form.password)); }
    } catch (err) { setError(err.message); if (err.pendingEmail) field('email', err.pendingEmail); }
    finally { setBusy(false); }
  }
  return <div className="pf-public"><header className="pf-topbar"><button className="pf-brand" onClick={() => go('landing')}><span><Zap size={22}/></span>DigiTalent<span className="pf-brand-ai">AI</span></button><nav aria-label="Khám phá DigiTalent"><button className="pf-link" onClick={()=>go('framework')}>Khung đào tạo</button>{page === 'landing' && <><a href="#pf-paths">Lộ trình</a><a href="#pf-courses">Khóa học</a><a href="#pf-business">Doanh nghiệp</a></>}<button className="pf-link" onClick={() => go('login')}>Đăng nhập</button><button className="pf-primary" onClick={() => go('register')}>Bắt đầu miễn phí <ArrowRight size={15}/></button></nav></header>
    {page === 'landing' ? <main>
      <section className="pf-landing-hero"><div><span className="pf-eyebrow">NĂNG LỰC SỐ CHO BƯỚC TIẾN NGHỀ NGHIỆP</span><h1>Vị trí bạn muốn.<br/><em>Lộ trình bạn cần.</em></h1><p>Biết mình đang ở đâu, học đúng khoảng thiếu và chứng minh tiến bộ bằng sản phẩm công việc.</p><div className="pf-actions"><button className="pf-primary" onClick={() => go('register', 'personal')}>Tìm lộ trình của tôi <ArrowRight size={17}/></button><button className="pf-secondary" onClick={() => go('register', 'enterprise')}>Đào tạo đội ngũ <Building2 size={17}/></button></div><div className="pf-trust"><span><Check size={14}/> Bắt đầu từ khóa cơ bản</span><span><Check size={14}/> Khung theo vị trí</span><span><Check size={14}/> Đo trước và sau</span></div></div><div className="pf-hero-roadmap"><div className="pf-roadmap-top"><span>LỘ TRÌNH CỦA BẠN</span><Target size={22}/></div><h2>Marketing số</h2><p>Từ kỹ năng nền tảng đến ứng dụng trong công việc</p>{[['01','Khám phá năng lực','Khảo sát theo vị trí'],['02','Học đúng khoảng thiếu','Cơ bản → Trung cấp → Nâng cao'],['03','Thực hành & kiểm chứng','Sản phẩm, phản hồi, tiến bộ']].map(([n,t,d]) => <div className="pf-journey-row" key={n}><span>{n}</span><div><strong>{t}</strong><small>{d}</small></div>{n === '02' && <span className="pf-tag">Bước tiếp theo</span>}</div>)}<div className="pf-roadmap-foot"><BookOpen size={18}/> 15 khóa · 5 lĩnh vực · 63 bài học</div></div></section>
      <section className="pf-section" id="pf-paths"><div className="pf-section-head"><div><span className="pf-eyebrow">HỌC VỚI MỤC TIÊU RÕ RÀNG</span><h2>Bạn muốn phát triển ở vị trí nào?</h2></div><span className="pf-muted">Khung tham chiếu có thể điều chỉnh theo doanh nghiệp</span></div><div className="pf-role-tabs">{JOB_ROLE_BENCHMARKS.map(item => <button key={item.roleId} className={item.roleId === role.roleId ? 'active' : ''} onClick={() => setRole(item)}>{item.roleTitle}</button>)}</div><div className="pf-path-preview"><div><Target size={30}/><h3>{role.roleTitle}</h3><p>Đánh giá năng lực hiện tại để chọn điểm bắt đầu. Mức độ yêu cầu được đối chiếu theo vị trí.</p><button className="pf-link" onClick={() => { field('targetRole', role.roleId); go('register', 'personal'); }}>Chọn mục tiêu này <ArrowRight size={15}/></button></div><div className="pf-path-stages">{[['01','Cơ bản','Hiểu và sử dụng công cụ số'],['02','Trung cấp','Chủ động áp dụng vào công việc'],['03','Nâng cao','Giải quyết vấn đề và cải tiến']].map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><small>{n === '01' ? 'Miễn phí' : 'Khóa lẻ hoặc gói học'}</small></article>)}</div></div></section>
      <section className="pf-section" id="pf-courses"><div className="pf-section-head"><div><span className="pf-eyebrow">BẮT ĐẦU TỪ NỀN TẢNG</span><h2>Mỗi kỹ năng, một bước tiến</h2></div><button className="pf-link" onClick={() => go('register')}>Khám phá 15 khóa <ArrowRight size={15}/></button></div><div className="pf-course-grid">{['A1-F','A3-F','A4-F'].map(id => { const course = ALL_DIGCOMP_COURSES[id]; return <article className="pf-course-card" key={id}><div className={`pf-course-art area-${id[1]}`}><BookOpen size={38}/><span>{id}</span></div><div><span className="pf-tag">Cơ bản · Miễn phí</span><h3>{course.title}</h3><p>{course.modules.length} bài học · {course.duration}</p><button className="pf-link" onClick={() => go('register', 'personal')}>Đăng ký để học <ArrowRight size={15}/></button></div></article>; })}</div></section>
      <section className="pf-business" id="pf-business"><div><span className="pf-eyebrow">DÀNH CHO DOANH NGHIỆP VỪA VÀ NHỎ</span><h2>Một đội ngũ.<br/>Nhiều vị trí. Cùng tiến bộ.</h2><p>Tạo doanh nghiệp, mời nhân viên bằng email, chọn khóa theo từng vị trí và theo dõi minh chứng thực hành.</p><button className="pf-primary" onClick={() => go('register', 'enterprise')}>Tạo doanh nghiệp dùng thử <ArrowRight size={16}/></button></div><div className="pf-business-steps">{['Xác thực email quản trị','Cấu hình gói và số khóa mỗi người','Nhân viên xác nhận lời mời','Học → nộp bài → thẩm định → đo lại'].map((text,i) => <div key={text}><span>0{i+1}</span><strong>{text}</strong><Check size={18}/></div>)}<p>Dùng thử 14 ngày · 5 nhân viên · tối đa 2 khóa cơ bản/người</p></div></section>
      <section className="pf-section"><div className="pf-section-head"><div><span className="pf-eyebrow">CHỌN CÁCH HỌC PHÙ HỢP</span><h2>Bắt đầu miễn phí, mở rộng khi cần</h2></div><small>Giá minh họa cho bản demo</small></div><div className="pf-plan-grid"><article><GraduationCap/><h3>Khám phá</h3><strong>Miễn phí</strong><p>5 khóa cơ bản, chọn mục tiêu nghề nghiệp và đánh giá đầu vào.</p><button className="pf-secondary" onClick={() => go('register','personal')}>Học cá nhân</button></article><article className="featured"><Target/><h3>{PLANS.personal.name}</h3><strong>{currency(PLANS.personal.price)}<small> / 30 ngày</small></strong><p>Các khóa sẵn sàng từ cơ bản đến nâng cao. Có lựa chọn mua từng khóa.</p><button className="pf-primary" onClick={() => go('register','personal')}>Xây lộ trình của tôi</button></article><article><Building2/><h3>Đào tạo doanh nghiệp</h3><strong>{currency(PLANS.team.price)}<small> / 30 ngày</small></strong><p>20 nhân viên, tối đa 10 khóa/người. Khởi đầu bằng gói dùng thử.</p><button className="pf-secondary" onClick={() => go('register','enterprise')}>Bắt đầu cho đội ngũ</button></article></div></section>
      <section className="pf-framework pf-section"><ShieldCheck size={28}/><div><h2>Khung rõ ràng. Phạm vi minh bạch.</h2><p>Tham chiếu DigComp 3.0 và Thông tư 02/2025/TT-BGDĐT. Có 15 khóa thuộc 5 lĩnh vực và giáo trình AI để xem trước; bảng đối chiếu đầu ra đang chờ chuyên gia thẩm định.</p><details><summary>Xem khung tham chiếu và cách ghi nhận năng lực</summary><p>DigComp 3.0 có 5 lĩnh vực, 21 năng lực và 4 mức; AI được tích hợp xuyên suốt. Thông tư có 6 miền, 24 năng lực và 8 bậc. Khảo sát 0–6 và hồ sơ 3 mức của dự án là thang nội bộ; không tự quy đổi sang hai khung.</p><a href="https://publications.jrc.ec.europa.eu/repository/handle/JRC144121" target="_blank" rel="noreferrer">DigComp 3.0</a> · <a href="https://datafiles.chinhphu.vn/cpp/files/vbpq/2025/01/02-bgddt.pdf" target="_blank" rel="noreferrer">Thông tư 02/2025</a></details></div></section>
    </main> : page === 'framework' ? <main><FrameworkWorkspace onOpenCourse={()=>go('register','personal')}/></main> : page === 'demo' ? <><div className="pf-auth-back"><button className="pf-link" onClick={() => go('login')}><ArrowLeft size={15}/> Đăng nhập bằng email</button></div><LoginPage onLogin={onLogin}/></> : <main className="pf-auth-layout"><aside><span className="pf-eyebrow">BẮT ĐẦU HÀNH TRÌNH</span><h1>{page === 'verify' ? 'Xác thực một lần. Sẵn sàng tiến bước.' : 'Một tài khoản. Học cho hôm nay và ngày mai.'}</h1><p>Email cá nhân hay email công ty đều có thể sử dụng. Không gian doanh nghiệp chỉ được cấp qua đăng ký quản trị hoặc lời mời đã xác nhận.</p><div className="pf-auth-steps"><span><Mail/> Email đã xác thực</span><span><Building2/> Doanh nghiệp đúng quyền</span><span><Target/> Mục tiêu đúng vị trí</span></div></aside><section className="pf-auth-card"><button className="pf-link" onClick={() => go('landing')}><ArrowLeft size={15}/> Trang giới thiệu</button><h2>{page === 'register' ? 'Tạo tài khoản' : page === 'verify' ? 'Xác thực email' : 'Chào mừng trở lại'}</h2>{error && <div className="pf-alert" role="alert">{error}</div>}{message && <div className="pf-success" role="status">{message}</div>}<form className="pf-form" onSubmit={submit}>
      {page === 'register' && <><div className="pf-choice"><button type="button" className={form.type === 'personal' ? 'active' : ''} onClick={() => field('type','personal')}><GraduationCap size={18}/> Tôi học cá nhân</button><button type="button" className={form.type === 'enterprise' ? 'active' : ''} onClick={() => field('type','enterprise')}><Building2 size={18}/> Tôi quản trị doanh nghiệp</button></div><label>Họ và tên<input required autoComplete="name" value={form.name} onChange={e=>field('name',e.target.value)}/></label></>}
      <label>Email<input required type="email" autoComplete="email" value={form.email} onChange={e=>field('email',e.target.value)} placeholder="ban@gmail.com hoặc ban@congty.vn"/></label>
      {page !== 'verify' && <label>Mật khẩu demo<input required minLength={8} type="password" autoComplete={page === 'register' ? 'new-password' : 'current-password'} value={form.password} onChange={e=>field('password',e.target.value)}/><small>Chỉ dùng mật khẩu thử nghiệm, không dùng mật khẩu thật.</small></label>}
      {page === 'register' && <>{form.type === 'enterprise' && <><label>Tên doanh nghiệp<input required value={form.company} onChange={e=>field('company',e.target.value)}/></label><div className="pf-form-two"><label>Ngành nghề<input required value={form.sector} onChange={e=>field('sector',e.target.value)}/></label><label>Quy mô nhân sự<input required type="number" min="1" max="500" value={form.size} onChange={e=>field('size',e.target.value)}/></label></div></>}<label>Vị trí muốn phát triển<select value={form.targetRole} onChange={e=>field('targetRole',e.target.value)}>{JOB_ROLE_BENCHMARKS.map(item=><option key={item.roleId} value={item.roleId}>{item.roleTitle}</option>)}</select></label><label className="pf-checkbox"><input type="checkbox" required checked={form.consent} onChange={e=>field('consent',e.target.checked)}/>Tôi đồng ý lưu dữ liệu thử trên trình duyệt để trải nghiệm; email và thanh toán được mô phỏng.</label></>}
      {page === 'verify' && <label>Mã xác thực 6 số<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code"/></label>}
      <button className="pf-primary" disabled={busy} type="submit">{busy ? 'Đang xử lý…' : page === 'register' ? 'Đăng ký & nhận mã xác thực' : page === 'verify' ? 'Xác thực email' : 'Đăng nhập'} <ArrowRight size={16}/></button>
    </form>{page === 'verify' ? <><button className="pf-link" onClick={() => { try { resendVerification(form.email); setMessage('Đã tạo mã mới trong hộp thư demo.'); setError(''); } catch(err) {setError(err.message);} }}>Gửi lại mã</button><DemoMailbox email={form.email}/><button className="pf-link" onClick={() => go('login')}>Đã xác thực? Đăng nhập</button></> : <div className="pf-auth-footer"><button className="pf-link" onClick={() => go(page === 'register' ? 'login' : 'register')}>{page === 'register' ? 'Đã có tài khoản? Đăng nhập' : 'Chưa có tài khoản? Đăng ký'}</button>{page === 'login' && <><button className="pf-link" onClick={() => go('verify')}>Email chưa xác thực?</button><details><summary>Không gian mẫu có sẵn</summary><p>Dành cho xem các vai trò và dữ liệu của bản demo trước.</p><button className="pf-secondary" onClick={() => go('demo')}>Mở tài khoản mẫu</button></details></>}</div>}</section></main>}
    <footer className="pf-footer"><strong>DigiTalent AI</strong><span>Học đúng kỹ năng · Đo được tiến bộ</span><small>Bản trải nghiệm FE · Dữ liệu lưu trên thiết bị hiện tại</small></footer>
  </div>;
}
