import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, X } from 'lucide-react';
import { DIAGNOSTIC_ASSESSMENT, ROLE_DIAGNOSTIC_ASSESSMENTS, POSITION_REQUIREMENTS } from '../data/mockMarketingFlow';
import { evaluateDiagnostic, generatePersonalizedRoadmap } from '../utils/competenceEngine';
import './workspaceRefresh.css';

export default function DiagnosticTestModal({ onComplete, onClose, targetRole = POSITION_REQUIREMENTS }) {
  const role = targetRole || POSITION_REQUIREMENTS;
  const questions = ROLE_DIAGNOSTIC_ASSESSMENTS[role.roleId] || DIAGNOSTIC_ASSESSMENT;
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState({});
  const [result, setResult] = useState(null);
  const question = questions[step];
  function finish() { const evaluation = evaluateDiagnostic(answers, role); setResult({ evaluation, roadmap: generatePersonalizedRoadmap(evaluation) }); }
  return <div className="modal-overlay" onClick={onClose}><div className="modal-content rf rf-diagnostic" style={{maxWidth:720}} onClick={e=>e.stopPropagation()}><div className="modal-header"><div><span className="rf-eyebrow">ĐÁNH GIÁ ĐẦU VÀO · {role.roleTitle}</span><h2>{result ? 'Kết quả khảo sát ban đầu' : `Câu ${step+1} / ${questions.length}`}</h2></div><button onClick={onClose} aria-label="Đóng"><X size={20}/></button></div><div className="modal-body rf-form">{!result ? <><div className="rf-note">Mỗi lĩnh vực có một câu hỏi. Kết quả giúp gợi ý lộ trình và chưa thay thế đánh giá thực hành.</div><div className="rf-diagnostic-track"><i style={{width:`${(step+1)/questions.length*100}%`}}/></div><span className="rf-eyebrow">{question.areaName} · {question.subCompetence}</span><h3>{question.question}</h3><div className="rf-options">{question.options.map((option,i)=><button key={i} className={answers[question.id]===i?'active':''} onClick={()=>setAnswers({...answers,[question.id]:i})}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div></> : <><div className="rf-metrics"><div className="rf-metric"><span>Lĩnh vực đạt mức yêu cầu</span><strong>{result.evaluation.passedCount}/{result.evaluation.totalAreas}</strong></div><div className="rf-metric"><span>Khoảng cách cộng dồn</span><strong>{result.evaluation.totalGap} mức</strong></div><div className="rf-metric"><span>Khóa gợi ý</span><strong>{result.roadmap.assigned.length}</strong></div></div><div className="rf-rows">{Object.values(result.evaluation.areaResults).map(area=><div className="rf-row" key={area.areaId}><div><strong>{area.areaName}</strong><small>{area.isMet?'Đạt mức yêu cầu trong bài khảo sát':'Cần học và kiểm chứng thêm'}</small></div><strong>{area.currentLevel}/{area.requiredLevel}</strong></div>)}</div><p className="rf-note">Kết quả ước tính từ 5 câu hỏi. Mức năng lực được xác nhận cần thêm bài thực hành và người quản lý thẩm định.</p></>}</div><div className="modal-footer">{!result ? <><button className="rf-secondary" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={15}/> Trước</button><button className="rf-primary" disabled={answers[question.id]===undefined} onClick={()=>step<questions.length-1?setStep(step+1):finish()}>{step<questions.length-1?'Câu tiếp theo':'Xem kết quả'} <ArrowRight size={15}/></button></> : <button className="rf-primary" onClick={()=>onComplete(result.evaluation,result.roadmap)}>Xem lộ trình học <ArrowRight size={15}/></button>}</div></div></div>;
}
