import React, { useState } from 'react';
import { ArrowRight, BookOpen, FileText, GitCompareArrows, ShieldCheck } from 'lucide-react';
import { ALL_DIGCOMP_COURSES } from '../data/courseCatalog';
import MANIFEST from '../data/frameworkSourceManifest.json';
import { COURSE_LEVELS, DEVELOPMENT_PRIORITIES, FRAMEWORK_ADAPTATION_NOTICE, FRAMEWORK_AREAS, FRAMEWORK_MAPPINGS, FRAMEWORK_SOURCES, FRAMEWORK_VERSION, getFrameworkCoverage, PROFICIENCY_SCALES } from '../data/frameworkRegistry';
import DemoLessonVideo from './DemoLessonVideo';
import './frameworkWorkspace.css';

export default function FrameworkWorkspace({ onOpenCourse, showDevelopment = false, initialSection = 'mapping' }) {
  const [section,setSection]=useState(initialSection === 'development' && !showDevelopment ? 'mapping' : initialSection);
  const [area,setArea]=useState('all');
  const [query,setQuery]=useState('');
  const [aiId,setAiId]=useState('AI-F');
  const [lessonIndex,setLessonIndex]=useState(0);
  const coverage=getFrameworkCoverage(ALL_DIGCOMP_COURSES);
  const rows=FRAMEWORK_MAPPINGS.filter(row=>(area==='all'||row.area===area)&&`${row.circularCode} ${row.name}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')));
  const aiCourse=MANIFEST.aiCourses.find(course=>course.id===aiId);
  const lesson=aiCourse.modules[lessonIndex];
  const menus=[['mapping','Đối chiếu khung',GitCompareArrows],['sources','Nguồn & giáo trình AI',FileText],...(showDevelopment?[['development','Ưu tiên phát triển',ShieldCheck]]:[])];
  return <section className="fw-workspace">
    <header className="fw-heading"><span className="fw-eyebrow">CƠ SỞ THIẾT KẾ ĐÀO TẠO</span><h1>DigComp 3.0 & Thông tư 02/2025</h1><p>Từ nguồn tham chiếu đến nội dung học và minh chứng năng lực.</p><div className="fw-source-links">{Object.values(FRAMEWORK_SOURCES).map(source=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">{source.name} · nguồn chính thức ↗</a>)}</div></header>
    <div className="fw-stats"><article><strong>5 / 21</strong><span>Lĩnh vực / năng lực DigComp 3.0</span></article><article><strong>6 / 24</strong><span>Miền / năng lực Thông tư</span></article><article><strong>{coverage.courseCount} + 3</strong><span>Khóa hiện có + giáo trình AI xem trước</span></article><article><strong>{coverage.approvedMappings} / 24</strong><span>Đối chiếu được chuyên gia xác nhận</span></article></div>
    <nav className="fw-tabs" aria-label="Khung và giáo trình">{menus.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon size={17}/>{label}</button>)}</nav>
    {section==='mapping' && <>
      <details className="fw-panel"><summary>Phân biệt các mức đang sử dụng</summary><div className="fw-scale-grid">{PROFICIENCY_SCALES.map(scale=><article key={scale.id}><h3>{scale.name}</h3><ul>{scale.labels.map(label=><li key={label}>{label}</li>)}</ul><p>{scale.note}</p></article>)}</div><p className="fw-note">Cùng tên “Cơ bản” chưa đủ để kết luận tương đương. Dự án cần đối chiếu đầu ra và tiêu chí; không tự quy đổi kết quả đã lưu.</p></details>
      <div className="fw-panel"><div className="fw-section-head"><div><h2>Bản đồ năng lực và khóa học</h2><p>{coverage.mappedTopics}/24 mã Thông tư xuất hiện trong {coverage.moduleCount} module hiện có. Đây là độ phủ chủ đề, chưa phải tỷ lệ đáp ứng chuẩn.</p></div><span className="fw-badge">Bản đối chiếu dự thảo</span></div><div className="fw-filters"><label>Lĩnh vực / miền<select value={area} onChange={e=>setArea(e.target.value)}><option value="all">Tất cả 24 năng lực</option>{FRAMEWORK_AREAS.map(item=><option key={item.id} value={item.id}>{item.id} · {item.id==='6'?item.circularName:item.name}</option>)}</select></label><label>Tìm năng lực<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Mã hoặc tên năng lực"/></label></div>
      <div className="fw-mapping-list">{rows.map(row=>{const courses=Object.values(ALL_DIGCOMP_COURSES).filter(course=>course.modules.some(module=>module.competenceCode===row.circularCode)).sort((a,b)=>['F','I','A'].indexOf(a.id.slice(-1))-['F','I','A'].indexOf(b.id.slice(-1)));return <details key={row.id} className="fw-mapping"><summary><span className="fw-code">{row.circularCode}</span><div><strong>{row.name}</strong><small>{row.area==='6'?'AI xuyên suốt · liên kết đề xuất':'Chủ đề đối chiếu'} · {courses.length?`${courses.length} khóa trong danh mục`:'3 giáo trình AI chưa vào danh mục'}</small></div><span className="fw-badge">Chờ thẩm định</span></summary><div className="fw-mapping-body"><p><strong>Thông tư {row.circularCode} → DigComp 3.0:</strong> {row.digcompCodes.join(', ')}</p><p>{row.rationale}</p><small>Nguồn nội dung: tai lieu/{row.sourceFile}</small><div className="fw-course-actions">{courses.map(course=><button key={course.id} onClick={()=>onOpenCourse(course)}><BookOpen size={15}/>{COURSE_LEVELS[course.id.slice(-1)]} · {course.id}<ArrowRight size={15}/></button>)}{row.area==='6' && <button onClick={()=>setSection('sources')}>Xem giáo trình AI <ArrowRight size={15}/></button>}</div></div></details>;})}{!rows.length && <p role="status">Không tìm thấy năng lực phù hợp.</p>}</div></div>
    </>}
    {section==='sources' && <>
      <section className="fw-panel"><h2>Tám tài liệu trong project</h2><p>Đã đọc nội dung gốc và ghi dấu phiên bản tệp. Tài liệu dự thảo cần rà soát chuyên môn trước khi công bố đạt chuẩn.</p><div className="fw-documents">{MANIFEST.sources.map(source=><details key={source.file}><summary><FileText size={18}/><div><strong>{source.file}</strong><small>{source.role}</small></div></summary><p>{source.paragraphs} đoạn văn được trích xuất · chờ chuyên gia rà soát</p><small>SHA-256 của tệp nguồn</small><code>{source.sha256}</code></details>)}</div></section>
      <section className="fw-panel"><span className="fw-eyebrow">MIỀN VI CỦA THÔNG TƯ</span><h2>Giáo trình ứng dụng AI</h2><p>Đọc nội dung và xem video minh họa từ giáo trình đã gửi. Phần này chưa tạo lượt học, kết quả kiểm tra, quyền mua hay xác nhận năng lực.</p><div className="fw-course-actions">{MANIFEST.aiCourses.map(course=><button key={course.id} className={aiId===course.id?'active':''} onClick={()=>{setAiId(course.id);setLessonIndex(0);}}>{COURSE_LEVELS[course.id.slice(-1)]} · 3 module</button>)}</div><h3>{aiCourse.title}</h3><label className="fw-lesson-select">Bài học AI<select value={lessonIndex} onChange={e=>setLessonIndex(Number(e.target.value))}>{aiCourse.modules.map((module,index)=><option key={module.id} value={index}>{module.competenceCode} · {module.title}</option>)}</select></label><DemoLessonVideo key={lesson.id} module={lesson}/><details className="fw-reading" open><summary>Mục tiêu và nội dung bài học</summary><ul>{lesson.objectives.map((text,i)=><li key={i}>{text}</li>)}</ul>{lesson.theory.map((text,i)=><p key={i}>{text}</p>)}</details><details className="fw-reading"><summary>Thực hành và sản phẩm cần nộp</summary>{lesson.practice.map((text,i)=><p key={i}>{text}</p>)}<strong>{lesson.product}</strong></details></section>
    </>}
    {section==='development' && showDevelopment && <section className="fw-panel"><h2>Các bước cần hoàn thiện</h2><p>Danh sách từ việc rà soát code và tài liệu hiện tại. P0: trước khi chốt nghiệp vụ; P1: trước pilot; P2: chuẩn bị triển khai thật.</p>{DEVELOPMENT_PRIORITIES.map(item=><details key={item.id} className="fw-priority"><summary><span className="fw-code">{item.priority}</span><strong>{item.title}</strong></summary><p><strong>Hiện trạng:</strong> {item.finding}</p><p><strong>Điều kiện hoàn thành:</strong> {item.acceptance}</p><small>Dữ liệu liên quan: {item.tables}</small></details>)}</section>}
    <footer className="fw-attribution"><p>{FRAMEWORK_ADAPTATION_NOTICE}</p><small>Phiên bản đối chiếu: {FRAMEWORK_VERSION}. Mức Highly advanced và bậc 7–8 chưa nằm trong phạm vi đào tạo hiện tại.</small></footer>
  </section>;
}
