import React, { useState } from 'react';
import { Download, FileCheck2 } from 'lucide-react';
import { ALL_DIGCOMP_COURSES } from '../data/courseCatalog';
import { listConfirmations, revokeConfirmation } from '../utils/learningConfirmations';

export function downloadCsv(rows) {
  const cell=value=>{const text=String(value??'');return `"${(/^[=+@\-\t\r]/.test(text)?"'"+text:text).replaceAll('"','""')}"`;};
  const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});
  const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='baocao-digitalent.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function LearningReports({organization,state}) {
  const [department,setDepartment]=useState('all');
  const people=organization.employees.filter(person=>department==='all'||state.directory.some(item=>item.employeeId===person.id&&item.departmentId===department));
  const rows=people.map(person=>{const enrollments=state.enrollments.filter(item=>item.employeeId===person.id);const profiles=state.profiles.filter(item=>item.employeeId===person.id);const runs=state.gapRuns.filter(item=>item.employeeId===person.id);return {person,enrollments,profiles,runs};});
  return <><section className="rf-panel rf-form"><div className="sys-section-heading"><div><h2>Báo cáo học tập & thực hành</h2><p>So sánh từ hoạt động đã phát sinh trong doanh nghiệp.</p></div><button className="rf-secondary" onClick={()=>downloadCsv([['Nhân viên','Vị trí','Lượt học','Hoàn thành','Năng lực xác nhận'],...rows.map(({person,enrollments,profiles})=>[person.name,organization.roles.find(role=>role.id===person.roleId)?.name,enrollments.length,enrollments.filter(item=>item.status==='COMPLETED').length,profiles.length])])}><Download size={15}/> Xuất CSV</button></div><label>Lọc phòng ban<select value={department} onChange={event=>setDepartment(event.target.value)}><option value="all">Toàn doanh nghiệp</option>{state.departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{rows.map(({person,enrollments,profiles,runs})=><details className="sys-profile" key={person.id}><summary><div><strong>{person.name}</strong><small>{enrollments.filter(item=>item.status==='COMPLETED').length}/{enrollments.length} lượt học hoàn thành · {profiles.length} năng lực đã xác nhận</small></div><span className="pw-status">{state.tasks.filter(item=>item.employeeId===person.id&&item.status==='SUBMITTED').length} bài chờ duyệt</span></summary>{enrollments.map(item=><div className="rf-row" key={item.id}><span>{ALL_DIGCOMP_COURSES[item.courseId]?.title}</span><strong>{item.progress}%</strong></div>)}{runs.length>=2 && runs[0].requirementSetId===runs[1].requirementSetId ? <p className="rf-note">Cùng khung v{runs[0].version}: tổng mức còn thiếu {runs[1].items.reduce((sum,item)=>sum+item.gap,0)} → {runs[0].items.reduce((sum,item)=>sum+item.gap,0)} ở hai lần phân tích gần nhất.</p> : <p className="pw-caption">Cần hai lần phân tích cùng phiên bản khung để so sánh trước/sau.</p>}</details>)}{!rows.length && <p className="ops-empty">Chưa có nhân viên trong phạm vi này.</p>}</section></>;
}
export function ConfirmationCenter({organization,user,admin,state,act}) {
  const records=listConfirmations(organization,admin?null:user.employeeId);
  const [selected,setSelected]=useState('');const [reason,setReason]=useState('');const [query,setQuery]=useState('');
  return <section className="rf-panel rf-form"><div className="sys-section-heading"><div><h2><FileCheck2 size={20}/> Xác nhận học tập</h2><p>Kết quả hoàn thành khóa được giữ riêng với năng lực công việc.</p></div><span className="pw-status">{records.length} kết quả</span></div><label>Tìm người học hoặc mã<input type="search" value={query} onChange={event=>setQuery(event.target.value)}/></label>{records.filter(record=>`${record.holder} ${record.code}`.toLowerCase().includes(query.toLowerCase())).map(record=><article className="sys-history" key={record.code}><strong>{record.holder} · {record.courseTitle}</strong><small>{record.completedAt} · {record.score}/100</small><code>{record.code}</code><span className="pw-status">{record.status==='REVOKED'?'Đã thu hồi':'Còn hiệu lực trong bản demo'}</span>{admin && record.status==='VALID' && <button className="pw-link" onClick={()=>{setSelected(record.code);setReason('');}}>Thu hồi xác nhận</button>}</article>)}{!records.length && <p className="ops-empty">Khi nhân viên hoàn thành bài cuối khóa, kết quả sẽ xuất hiện tại đây.</p>}{selected && <form className="rf-form sys-submission" onSubmit={event=>{event.preventDefault();const result=act(()=>{revokeConfirmation(organization,selected,reason,user.id);return true;},'Đã thu hồi xác nhận và thông báo cho người học.');if(result)setSelected('');}}><strong>Thu hồi {selected}</strong><label>Lý do nội bộ<textarea required value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="rf-actions"><button type="button" className="rf-secondary" onClick={()=>setSelected('')}>Hủy</button><button type="submit" className="rf-primary">Xác nhận thu hồi</button></div></form>}{admin && <details className="rf-prompt"><summary>Lịch sử tra cứu · {state.verificationLogs.length} lượt</summary>{state.verificationLogs.slice(0,20).map(item=><p key={item.id}>{item.code} · {item.status} · {new Date(item.createdAt).toLocaleString('vi-VN')}</p>)}</details>}</section>;
}

